### ISSUE TITLE
Android build failure

### ISSUE THREAD

**Issue by Ross-Rawlins** [mapsplugin/cordova-plugin-googlemaps#1208]
Below is the log when I run android build.

error: cannot access AbstractSafeParcelable
    Builder builder = LatLngBounds.builder();
                                  ^
  class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileArmv7DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by Fayozjon** [comment]
try to reinstall plugin, remove it and add again

**Comment by Ross-Rawlins** [comment]
I have doe this a few times. and its still producing this error

**Comment by starostin** [comment]
I have the same issue

**Comment by Ross-Rawlins** [comment]
Glad I am not the only one

**Comment by TomDemulierChevret** [comment]
Same issue here.

**Comment by zwacky** [comment]
having this issue as well.
using github repo directly.

**Comment by TomDemulierChevret** [comment]
The build doesn't fail if you downgrade the plugin to version 1.3.9.

**Comment by zwacky** [comment]
@TomDemulierChevret so you mean:

```
ionic plugin add https://github.com/phonegap-googlemaps-plugin/cordova-plugin-googlemaps#1.3.9 --variable [...]
```
?

**Comment by wf9a5m75** [comment]
@Ross-Rawlins @zwacky 
Do you install the map plugin into a new project?
I **STRONGLY** recommend you should try this plugin **WITHOUT** other plugins at the first.

**Comment by zwacky** [comment]
I'll try my snippet for 1.3.9 in 2 hours and report back. maybe only the upstream build is broken.

**Comment by TomDemulierChevret** [comment]
@zwacky I used npm as the source (cordova-plugin-googlemaps) but yeah github should work too.

My build with Android works fine with 1.3.9 but this downgrade broke my iOS build wich working fine (both with 1.4.0 and whichever version was on githhub 2 weeks ago).

**Comment by TomDemulierChevret** [comment]
Ok, the version 1.3.9 on npm seem's to be broken for iOS, but not the one on github.
Builds on both platform seem's to be working with : https://github.com/mapsplugin/cordova-plugin-googlemaps#1.3.9

**Comment by wf9a5m75** [comment]
Npm is already 1.4.0
https://www.npmjs.com/package/cordova-plugin-googlemaps

**Comment by Ross-Rawlins** [comment]
I installed the plugin first by itself but as soon as I added other plugins its breaks. This means this plugin is only good by itself which makes no sense.

I have done a clean install. I have removed the plugin and re added it. I have removed and re added platforms. I have rest my plugins state. I first had a build issue on IOS now its android. The android break came on the last commit.

@TomDemulierChevret can you confirm you are working both for 1.3.9 but you had to download it yourself and not install through npm.

**Comment by wf9a5m75** [comment]
@Ross-Rawlins Forget about 1.3.9. It's no more supported.

And please create a new project, don't use your project at first.

```
$> cordova create HelloWorld
$> cd HelloWorld
$> cordova platform add platform android ios
$> cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."
```

Edit `www/index.html`
https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Tutorial-for-Mac#6-change-the-wwwindexhtml

```
$> cordova run android (or iOS)
```

**Comment by zwacky** [comment]
@wf9a5m75 that's not going to be a solution to start afresh for lots of devs out there. me included :S

yeah, I'm getting force closes upon startup when using the 1.3.9 plugin version. but I can't build it with the master version.

**Comment by wf9a5m75** [comment]
@zwacky The point is you should separate the problem.
This plugin implementation is very special. And other plugins may affect to this plugin (frequently occur).

That's why you should create a clean project and test it before using your application.

**Comment by Ross-Rawlins** [comment]
I have tried the solution of a new priject and it will work until you re add a plugin. This plugin doesnt seem isolated. @wf9a5m75 I need a build to work and I can address teh supported stuff later. Does 1.3.9 work can I build both ios and android?

**Comment by wf9a5m75** [comment]
No more support for 1.3.9

Use 1.4.0 (npm and github are the same)

**Comment by Ross-Rawlins** [comment]
@wf9a5m75 BUT 1.4.0 does not build on android. so is there a plan it fix this so that you can run another plugin on the same app??

**Comment by Ross-Rawlins** [comment]
why have you hard coded your plugin play services to 9.8.0

**Comment by Ross-Rawlins** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/plugin.xml#L49

can and swap out this to have a + and it solves the build issue

**Comment by pke** [comment]
Yes, the problem is the GMS pinning in https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/044067265ede42f2d9c2d6db530ad44eab0e37e9/plugin.xml#L48 f

Why was that done? No plugin is supposed to do that. If the mapstyles introduced in 04406726 requires 9.8.0 then write that in the README and not pin the version.

**Comment by wf9a5m75** [comment]
The reason is if your environment's google play services library is old, but specify '+', some building tool does not update.
It's gonna be another building error.

I don't support the compatibility with another plugin.
You should modify the plugin version by yourself in local.

**Comment by wf9a5m75** [comment]
The google play services is already 10.0.1
But the PhoneGap Build does not catch up quickly.
The 9.8.0 is the version which is the most cloud building services are able to build this plugin, and including tje styles feaature.

**Comment by wf9a5m75** [comment]
If you think this is problem, you can fork or git clone , then modify the version.
(This is open source)
I don't revert the plugin.xml

**Comment by Pushplaybang** [comment]
@wf9a5m75 @pke surely you can see that you've broken the ability for a number of people to build this plugin, and provided no recourse or documentation about how or why.

**Comment by zwacky** [comment]
@Pushplaybang hey there, let's concentrate on fixing this together rather than pointing fingers.

**Comment by fmendoza** [comment]
Same here. Any workaround or solution to this issue?

**Comment by wf9a5m75** [comment]
Read here
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1200#issuecomment-263515708

**Comment by fmendoza** [comment]
Thank you. In my case I edited the plugin.xml from AdMob, LocationRequest and Google Analytics plugins and now everything is working great again. Not ideal, but it solves the issue.

**Comment by pke** [comment]
You should just edit this plugins xml and remove the version pinning. It's bad style anyway. This makes updating all the other plugins you mentioned much easier because the adhere to cooperative style of plugins. With each update of those plugins you would have to update their local plugin.xml

**Comment by christocracy** [comment]
If i had a dollar every time some 3rd-party plugin **PINNED** their `play-services` dependencies at some particular version, **breaking my plugins**...

You **cannot** dictate the `play-services` version that **all** other plugins must use.

```xml
<framework src="com.google.android.gms:play-services-location:9.8.0" />
```

**You must do this**
```xml
<framework src="com.google.android.gms:play-services-location:+" />
```

**Comment by zwacky** [comment]
any downsides upon unpinning the version? otherwise see referenced PR otherwise.

**Comment by wf9a5m75** [comment]
Read here what the risk of specifying the latest version.
http://blog.danlew.net/2015/09/09/dont-use-dynamic-versions-for-your-dependencies/

I don't mind if you modify the plugin.xml in your local or the forked repo.

**Comment by christocracy** [comment]
It's the **application's** responsibility to pin a particular version -- **NOT** a dependency.

A dependency **cannot** dictate to the app and all other dependencies which particular version of some shared dependency is to be used.

**Comment by pke** [comment]
And since the pinned 9.8.0 is obviously not working well with other dependencies the article @wf9a5m75 mentioned is rendered wrong.

@christocracy How would we pin the version in the cordova app?

**Comment by christocracy** [comment]
I've never tried it but I'd start with `platforms/android/build.gradle`

**Comment by wf9a5m75** [comment]
@christocracy Are you able to response all build issues and detect the version numbers for this plugin?
Building success, bud the plugin crashes for some reason?
Do you inspect all claims?
Probably not, and you don't want to do that.

Even for me, that's really difficult. The app developers typically don't want to share their app code, does not provide enough log, knowledge level might be less...etc.
But in the past three years, I faces couple of times, the google play services latest version leads to  this type of issues.
And specifying `+` means some building environments omit the update of the library.
It leads to this type of issue also.

For example, the styled map type with this plugin requires at least 9.8.0 of the Google Play Services.
But specifying `+`, some environment does not update the library if there is the google play services little older version.
Then build would be success, but the app crashes.

Who is going to inspect this error? Probably not.

----

Building error (with conflict) is easy. Just modify the plugin.xml by hand in their local.

-----

The same reason, this plugin also specify the particular version.
(But more strongly)
https://github.com/fechanique/cordova-plugin-fcm/blob/master/src/android/FCMPlugin.gradle

**Comment by wf9a5m75** [comment]
I know you guys what you mean, but you guys also must my concern.
Then find the solution for both is acceptable.

**Comment by christocracy** [comment]
I don't actually use this plugin.  Two of my customers of do.  They're posting issues on my repos because this plugin is conflicting with mine.

Over at NativeScript, here's what the [nativescript-google-maps](https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/platforms/android/include.gradle#L10) plugin does:

Way smarter.  Let the *application* provide that property.  Dependencies have **no right** to dictate the version of such a widely used dependency such as `play-services`.  This is the responsibility of the app.

```
dependencies {
	def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion : '+'
	compile "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
}
```

**Comment by wf9a5m75** [comment]
```
dependencies {
	def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion : '+'
	compile "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
}
```
Thanks.
This idea is better, but I need to test with well-known build environments.
At least, the intel XDK fails specifying `+`.

----

And I don't know why your plugin conflict with this plugin (this is just curiosity)
It seems you implement the google maps native sdks by yourself.
Your plugin does not use this plugin internally.

**Comment by christocracy** [comment]
Intel XDK is a piece of junk stuck on Cordova 3.x.  I suspect that service no longer employs a full-time engineering team.  Why would you worry about supporting them?  I refuse to.

My plugin [cordova-background-geolocation-lt](https://github.com/transistorsoft/cordova-background-geolocation-lt)
 is a geolocation plugin.  It spits out locations.  It doesn't rely upon any particular UI component (or Cordova:  [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation), [nativescript-background-geolocation](https://github.com/transistorsoft/nativescript-background-geolocation-lt)).

**Comment by wf9a5m75** [comment]
Thanks, I see, your plugin just obtaining the location, and the app developers use this plugin for UI.
That's interesting.

----

Anyway, I will test with something based on the suggested idea.
If I confirm with no problem, change the plugin.xml.

**Comment by hugomosh** [comment]
So... , I am using both googleplus and google maps in an ionic2 project.
I had the problem and pinning the plugin.xml of the googleplus and removing and adding the platform android fixed the problem.
But what should I expect. Doing this for all my devs? or I see a fix comming?

**Comment by Fayozjon** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/androi
d/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.2.0.



BUILD FAILED

Total time: 12.502 secs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7DebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/androi
d/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.2.0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by Fayozjon** [comment]
p.s. I guess its because FCM plugin using 
9.2.0 version

**Comment by Fayozjon** [comment]
If im trying to build via 9.2.0 im getting such error


```
 symbol: class MapStyleOptions
:\newapp\MyApteka\platforms\android\src\plugin\google\maps\GoogleMaps.java:638: error: cannot find symbol
               map.setMinZoomPreference((float)zoom.getDouble("minZoom"));
                  ^
 symbol:   method setMinZoomPreference(float)
 location: variable map of type GoogleMap
:\newapp\MyApteka\platforms\android\src\plugin\google\maps\GoogleMaps.java:641: error: cannot find symbol
               map.setMaxZoomPreference((float)zoom.getDouble("maxZoom"));
                  ^
 symbol:   method setMaxZoomPreference(float)
 location: variable map of type GoogleMap
:\newapp\MyApteka\platforms\android\src\plugin\google\maps\PluginMap.java:91: error: cannot find symbol
     MapStyleOptions styleOptions = new MapStyleOptions(styles);
     ^
 symbol:   class MapStyleOptions
 location: class PluginMap
:\newapp\MyApteka\platforms\android\src\plugin\google\maps\PluginMap.java:91: error: cannot find symbol
     MapStyleOptions styleOptions = new MapStyleOptions(styles);
                                        ^
 symbol:   class MapStyleOptions
 location: class PluginMap
:\newapp\MyApteka\platforms\android\src\plugin\google\maps\PluginMap.java:182: error: cannot find symbol
         map.setMinZoomPreference((float)zoom.getDouble("minZoom"));
            ^
 symbol:   method setMinZoomPreference(float)
 location: variable map of type GoogleMap
:\newapp\MyApteka\platforms\android\src\plugin\google\maps\PluginMap.java:185: error: cannot find symbol
         map.setMaxZoomPreference((float)zoom.getDouble("maxZoom"));
            ^
 symbol:   method setMaxZoomPreference(float)
 location: variable map of type GoogleMap
ote: Some input files use or override a deprecated API.
ote: Recompile with -Xlint:deprecation for details.
ote: E:\newapp\MyApteka\platforms\android\src\org\apache\cordova\file\AssetFilesystem.java uses unchecked or unsafe operations.
ote: Recompile with -Xlint:unchecked for details.
```

**Comment by Fayozjon** [comment]
@wf9a5m75  After building success im not able to run app.
It crashes. Says Application cannot be loaded..
Logcat at attachments. App id is samapteka.uz
[logcat.txt](https://github.com/mapsplugin/cordova-plugin-googlemaps/files/644007/logcat.txt)

**Comment by sunny061** [comment]
+1

Facing the same error...

error: cannot access AbstractSafeParcelable
Builder builder = LatLngBounds.builder();
^

**Comment by alex116** [comment]
I just updated my sdk tools, platform-tools, support repository, play services and google-repository because my nexus that had recently gotten the 7.1.1 update, wasn't letting me debug the chrome webview. Updating fixed the webview debugging issue but after building my project again I started seeing exactly this error. I am using the maps 1.4.0 release and it was working fine until I updated the mentioned packages.

**Comment by sabirali007** [comment]
+1

**Comment by tchinou1** [comment]
+1 Here !

**Comment by Fayozjon** [comment]
SOLVED:

UPDATE GOOGLE SERVICES and change BUILD API level 23 and higher

**Comment by albertora** [comment]
I'm getting the same error using the last update google services and sdk Android 25

**Comment by pke** [comment]
It's all been explained in this issue. U have to fix the wrong specific version pinning of this plugin to a broader `+` dependency

**Comment by albertora** [comment]
I've already change the plugin dependency but this not fix this error, thanks for your response

**Comment by gonadn** [comment]
this worked for me:

# Project target.
target=android-25
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:support-v4:+
cordova.system.library.2=com.android.support:appcompat-v7:+
cordova.system.library.3=com.google.android.gms:play-services-maps:10.0.0
cordova.system.library.4=com.google.android.gms:play-services-location:10.0.0
cordova.system.library.5=com.google.android.gms:play-services-maps:10.0.0
cordova.system.library.6=com.google.android.gms:play-services-location:10.0.0
cordova.system.library.7=com.google.android.gms:play-services-maps:10.0.0
cordova.system.library.8=com.google.android.gms:play-services-location:10.0.0
cordova.system.library.9=com.google.android.gms:play-services-ads:+
cordova.system.library.10=com.google.android.gms:play-services-maps:10.0.0
cordova.system.library.11=com.google.android.gms:play-services-location:10.0.0

**Comment by jcbermu** [comment]
This worked for me after installing Firebase Plugin.

**Comment by grapemix** [comment]
@gonadn , you are the man!

**Comment by cedvict** [comment]
Hi, This plugin doesn't work on platform android. I'm thinking that some file missing. src/android/plugin/google/maps/Map.java
