### ISSUE TITLE
Error at create a build with Xcode 7.3

### ISSUE THREAD

**Issue by diegognt** [mapsplugin/cordova-plugin-googlemaps#912]
at run `ionic build ios` I got this error:

```
fatal error: 'MFGoogleMapAdditions/GMSCoordinateBounds+Geometry.h' file not found
#import "MFGoogleMapAdditions/GMSCoordinateBounds+Geometry.h"
```
systema set up:

```
ionic plugin list
com.googlemaps.ios 1.11.1 "Google Map iOS SDK for Cordova"
cordova-plugin-console 1.0.2 "Console"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-geolocation 2.1.0 "Geolocation"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-splashscreen 3.2.1 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.1 "Whitelist"
ionic-plugin-keyboard 2.0.1 "Keyboard"
plugin.google.maps 1.3.9 "phonegap-googlemaps-plugin"
```

node version: 4.2.2
Xcode 7.3 Build version 7D175
cordova-ios 3.9.2

**Comment by PapyElGringo** [comment]
+1

**Comment by cvaliere** [comment]
+1

**Comment by wf9a5m75** [comment]
Ok,

**Comment by wf9a5m75** [comment]
This should be fixed. Try again please.

**Comment by diegognt** [comment]
No I got at try to run this:

```
/projectPath/platforms/ios/OU Innovate/Plugins/plugin.google.maps/MyPluginLayer.m:43:32: error: property 'scrollView' not found on object of type 'UIView *'
  float offsetX = self.webView.scrollView.contentOffset.x;// + self.mapCtrl.view.frame.origin.x;
                               ^
/projectPath/platforms/ios/OU Innovate/Plugins/plugin.google.maps/MyPluginLayer.m:44:32: error: property 'scrollView' not found on object of type 'UIView *'
  float offsetY = self.webView.scrollView.contentOffset.y;// + self.mapCtrl.view.frame.origin.y;
                               ^
/projectPath/platforms/ios/OU Innovate/Plugins/plugin.google.maps/MyPluginLayer.m:106:32: error: property 'scrollView' not found on object of type 'UIView *'
  float offsetX = self.webView.scrollView.contentOffset.x;// + self.mapCtrl.view.frame.origin.x;
                               ^
/projectPath/platforms/ios/OU Innovate/Plugins/plugin.google.maps/MyPluginLayer.m:107:32: error: property 'scrollView' not found on object of type 'UIView *'
  float offsetY = self.webView.scrollView.contentOffset.y;// + self.mapCtrl.view.frame.origin.y;
                               ^
/projectPath/platforms/ios/OU Innovate/Plugins/plugin.google.maps/MyPluginLayer.m:131:39: error: property 'scrollView' not found on object of type 'UIView *'
  rectangle.size.width = self.webView.scrollView.contentSize.width;
                                      ^
/projectPath/Plugins/plugin.google.maps/MyPluginLayer.m:137:39: error: property 'scrollView' not found on object of type 'UIView *'
  rectangle.size.width = self.webView.scrollView.contentSize.width;
                                      ^
/projectPath/platforms/ios/OU Innovate/Plugins/plugin.google.maps/MyPluginLayer.m:138:40: error: property 'scrollView' not found on object of type 'UIView *'
  rectangle.size.height = self.webView.scrollView.contentSize.height;
```

**Comment by wf9a5m75** [comment]
Did you reinstall the plugin from git repository?

**Comment by diegognt** [comment]
yes

**Comment by diegognt** [comment]
first `sudo rm platforms plugins` then `ionic state restore` then `ionic build ios` and `ionic run ios`

**Comment by wf9a5m75** [comment]
I'm not familiar with ionic :(

**Comment by diegognt** [comment]
this how is the plugin object on package.json
```
{
      "id": "cordova-plugin-googlemaps",
      "locator": "https://github.com/mapsplugin/cordova-plugin-googlemaps.git",
      "variables": {
        "API_KEY_FOR_ANDROID": "key",
        "API_KEY_FOR_IOS": "key"
      }
    }
```

**Comment by diegognt** [comment]
sorry wf9a5m75 I just delete all the content on the folder that contains the plugins and rebuild the project

**Comment by wf9a5m75** [comment]
OK, I also confirmed that the original issue was fixed.

**Comment by diegognt** [comment]
but still not working, same error:

```
/projectPath/platforms/ios/project/Plugins/plugin.google.maps/MyPluginLayer.m:43:32: error: property 'scrollView' not found on object of type 'UIView *'
  float offsetX = self.webView.scrollView.contentOffset.x;// + self.mapCtrl.view.frame.origin.x;
                               ^
/projectPath/platforms/ios/project/Plugins/plugin.google.maps/MyPluginLayer.m:44:32: error: property 'scrollView' not found on object of type 'UIView *'
  float offsetY = self.webView.scrollView.contentOffset.y;// + self.mapCtrl.view.frame.origin.y;
                               ^
/projectPath/platforms/ios/project/Plugins/plugin.google.maps/MyPluginLayer.m:106:32: error: property 'scrollView' not found on object of type 'UIView *'
  float offsetX = self.webView.scrollView.contentOffset.x;// + self.mapCtrl.view.frame.origin.x;
                               ^
/projectPath/platforms/ios/project/Plugins/plugin.google.maps/MyPluginLayer.m:107:32: error: property 'scrollView' not found on object of type 'UIView *'
  float offsetY = self.webView.scrollView.contentOffset.y;// + self.mapCtrl.view.frame.origin.y;
                               ^
/projectPath/platforms/ios/project/Plugins/plugin.google.maps/MyPluginLayer.m:131:39: error: property 'scrollView' not found on object of type 'UIView *'
  rectangle.size.width = self.webView.scrollView.contentSize.width;
                                      ^
/projectPath/Plugins/plugin.google.maps/MyPluginLayer.m:137:39: error: property 'scrollView' not found on object of type 'UIView *'
  rectangle.size.width = self.webView.scrollView.contentSize.width;
                                      ^
/projectPath/platforms/ios/project/Plugins/plugin.google.maps/MyPluginLayer.m:138:40: error: property 'scrollView' not found on object of type 'UIView *'
  rectangle.size.height = self.webView.scrollView.contentSize.height;
```

**Comment by wf9a5m75** [comment]
Um, that is not related with `GMSCoordinateBounds+Geometry.h`. I wonder.

**Comment by diegognt** [comment]
Do you want that I create another issue for that error?

**Comment by wf9a5m75** [comment]
Yes, please. How about @PapyElGringo and @cvaliere ?

**Comment by cvaliere** [comment]
yes, it's ok
we have a crash at Marker.m though, we'll create another issue
